"""contacts table

Revision ID: 242ce9797be5
Revises: 419e58771447
Create Date: 2019-09-06 16:10:03.631822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '242ce9797be5'
down_revision = '419e58771447'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=140), nullable=True),
    sa.Column('lastname', sa.String(length=140), nullable=True),
    sa.Column('email', sa.String(length=140), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_timestamp'), 'contact', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contact_timestamp'), table_name='contact')
    op.drop_table('contact')
    # ### end Alembic commands ###
