"""contacts table

Revision ID: 24f33ad1ed97
Revises: 413fad2904bf
Create Date: 2019-09-07 02:25:17.912792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24f33ad1ed97'
down_revision = '413fad2904bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('address', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'address')
    # ### end Alembic commands ###
