"""contacts table

Revision ID: 413fad2904bf
Revises: 242ce9797be5
Create Date: 2019-09-06 23:06:47.868464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '413fad2904bf'
down_revision = '242ce9797be5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('owner', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'owner')
    # ### end Alembic commands ###
