"""contacts table

Revision ID: 91b893f7e9e6
Revises: 24f33ad1ed97
Create Date: 2019-09-18 19:09:36.876826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91b893f7e9e6'
down_revision = '24f33ad1ed97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contact_timestamp', table_name='contact')
    op.drop_constraint(None, 'contact', type_='foreignkey')
    op.drop_column('contact', 'address')
    op.drop_column('contact', 'timestamp')
    op.drop_column('contact', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.add_column('contact', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    op.add_column('contact', sa.Column('address', sa.VARCHAR(length=140), nullable=True))
    op.create_foreign_key(None, 'contact', 'user', ['user_id'], ['id'])
    op.create_index('ix_contact_timestamp', 'contact', ['timestamp'], unique=False)
    # ### end Alembic commands ###
